FROM php:8.0.9-apache

LABEL maintainer="Geovane Fonseca de Sousa Santos <geovanefss@gmail.com>"

EXPOSE 80
EXPOSE 443

ENV TZ 'Europe/Lisbon'
RUN echo $TZ > /etc/timezone && \
apt-get update && apt-get install -y --allow-unauthenticated tzdata && \
rm /etc/localtime && \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
dpkg-reconfigure -f noninteractive tzdata

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

ADD oracle/instantclient-basic-linux.x64-12.2.0.1.0.tar.gz /usr/local
ADD oracle/instantclient-sdk-linux.x64-12.2.0.1.0.tar.gz /usr/local
ADD oracle/instantclient-sqlplus-linux.x64-12.2.0.1.0.tar.gz /usr/local

RUN useradd -m -u 1000 winuser && usermod -g www-data winuser

RUN apt-get update && apt-get -y install libzip-dev && apt-get -y install zip && apt-get -y install unzip \
  && ln -s /usr/local/instantclient_12_2 /usr/local/instantclient \
  && ln -s /usr/local/instantclient/libclntsh.so.* /usr/local/instantclient/libclntsh.so \
  && ln -s /usr/local/instantclient/lib* /usr/lib \
  && ln -s /usr/local/instantclient/sqlplus /usr/bin/sqlplus \
  && chmod 755 -R /usr/local/instantclient \
  && docker-php-ext-configure oci8 --with-oci8=instantclient,/usr/local/instantclient \
  && docker-php-ext-install oci8 \
  && docker-php-ext-install pdo_mysql exif opcache \
  && docker-php-ext-install mysqli \
  && apt-get install -y libicu-dev libaio-dev libxml2-dev libjpeg-dev libpng-dev libfreetype6-dev \
  && docker-php-ext-install intl soap dom \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install gd \
  && docker-php-ext-install zip \
  && docker-php-ext-install sockets \
  && apt-get install -y imagemagick \
  && apt-get purge -y --auto-remove \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /var/www/html/public \
  && a2enmod headers rewrite \
  && apt-get clean

WORKDIR /var/www/html

COPY ./apache/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache/charset.conf /etc/apache2/conf-available/charset.conf
COPY ./php/timezone.ini /usr/local/etc/php/conf.d/timezone.ini
COPY ./php/vars-dev.ini /usr/local/etc/php/conf.d/vars.ini

RUN cp -f "/usr/local/etc/php/php.ini-development" /usr/local/etc/php/php.ini
